name: Compilar para macOS

on: [push, workflow_dispatch]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Instalar dependencias
        run: |
          pip install PyQt6 gTTS pyinstaller
      - name: Compilar ejecutable de macOS
        run: |
          pyinstaller --onefile --windowed --name "ContadorDeUnidades" --add-data "assets:assets" main.py
      - name: Subir artefacto para Mac
        uses: actions/upload-artifact@v4
        with:
          name: ContadorDeUnidades-macOS
          path: dist/
